server:
    port : 8082
    context-path: /dpe-app-ms-internaldata

##Configuracion Service Path CXF
cxf:
  path : /soap

#Configuration Spring
spring:
  application:
          name: dpe-app-ms-internaldata
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mysql://localhost:3306/internaldata
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
#CONFIGURACION PARA EL CORREO ELECTRONICO
  mail:
    host: smtp.gmail.com
    port: 587
    username: villarreal.benji@gmail.com
    password: yfdpopygyxifrfka
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
#Configuration Eureka
eureka:
  client:
    enable: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}