server:
    port : 8081

##Configuracion Service Path CXF
cxf:
  path : /soap

#Configuration Spring
spring:
  application:
          name: dpe-app-ws-orquestador

#Configuration Eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    #serviceUrl:
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}